# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

use_frameworks!

target 'Restaurante' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  
  # UI
  pod 'IQKeyboardManagerSwift'
  pod 'GoogleMaps'
  
  # Servicios
  pod 'Alamofire'
  pod 'AlamofireImage'

end
